#pragma once

#include <GLFW/glfw3.h>
#include <string>
#include <vector>

#define DEVICE_OFFSET_KEYBOARD 0
#define DEVICE_OFFSET_MOUSE 1000
#define DEVICE_OFFSET_JOYSTICK 2000
#define DEVICE_OFFSET_GAMEPAD 3000

using InputCode = int;

constexpr InputCode ToInputCode(int code, int device_offset)
{
    return code + device_offset;
};

enum InputCodes
{
    Invalid          = -1,

    // Keyboard

    Key_Space        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_SPACE,
    Key_Apostrophe   = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_APOSTROPHE,
    Key_Comma        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_COMMA,
    Key_Minus        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_MINUS,
    Key_Period       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_PERIOD,
    Key_Slash        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_SLASH,

    Key_0 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_0,
    Key_1 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_1,
    Key_2 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_2,
    Key_3 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_3,
    Key_4 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_4,
    Key_5 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_5,
    Key_6 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_6,
    Key_7 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_7,
    Key_8 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_8,
    Key_9 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_9,

    Key_Semicolon = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_SEMICOLON,
    Key_Equal     = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_EQUAL,

    Key_A = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_A,
    Key_B = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_B,
    Key_C = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_C,
    Key_D = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_D,
    Key_E = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_E,
    Key_F = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F,
    Key_G = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_G,
    Key_H = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_H,
    Key_I = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_I,
    Key_J = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_J,
    Key_K = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_K,
    Key_L = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_L,
    Key_M = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_M,
    Key_N = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_N,
    Key_O = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_O,
    Key_P = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_P,
    Key_Q = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_Q,
    Key_R = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_R,
    Key_S = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_S,
    Key_T = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_T,
    Key_U = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_U,
    Key_V = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_V,
    Key_W = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_W,
    Key_X = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_X,
    Key_Y = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_Y,
    Key_Z = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_Z,

    Key_LeftBracket  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_LEFT_BRACKET,
    Key_Backslash    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_BACKSLASH,
    Key_RightBracket = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_RIGHT_BRACKET,
    Key_GraveAccent  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_GRAVE_ACCENT,
    Key_World1       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_WORLD_1,
    Key_World2       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_WORLD_2,

    Key_Escape      = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_ESCAPE,
    Key_Enter       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_ENTER,
    Key_Tab         = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_TAB,
    Key_Backspace   = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_BACKSPACE,
    Key_Insert      = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_INSERT,
    Key_Delete      = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_DELETE,

    Key_Right       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_RIGHT,
    Key_Left        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_LEFT,
    Key_Down        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_DOWN,
    Key_Up          = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_UP,

    Key_PageUp      = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_PAGE_UP,
    Key_PageDown    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_PAGE_DOWN,
    Key_Home        = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_HOME,
    Key_End         = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_END,

    Key_CapsLock    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_CAPS_LOCK,
    Key_ScrollLock  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_SCROLL_LOCK,
    Key_NumLock     = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_NUM_LOCK,
    Key_PrintScreen = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_PRINT_SCREEN,
    Key_Pause       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_PAUSE,

    Key_F1  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F1,
    Key_F2  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F2,
    Key_F3  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F3,
    Key_F4  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F4,
    Key_F5  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F5,
    Key_F6  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F6,
    Key_F7  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F7,
    Key_F8  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F8,
    Key_F9  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F9,
    Key_F10 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F10,
    Key_F11 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F11,
    Key_F12 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F12,
    Key_F13 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F13,
    Key_F14 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F14,
    Key_F15 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F15,
    Key_F16 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F16,
    Key_F17 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F17,
    Key_F18 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F18,
    Key_F19 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F19,
    Key_F20 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F20,
    Key_F21 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F21,
    Key_F22 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F22,
    Key_F23 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F23,
    Key_F24 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F24,
    Key_F25 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_F25,

    Key_KP_0 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_0,
    Key_KP_1 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_1,
    Key_KP_2 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_2,
    Key_KP_3 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_3,
    Key_KP_4 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_4,
    Key_KP_5 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_5,
    Key_KP_6 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_6,
    Key_KP_7 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_7,
    Key_KP_8 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_8,
    Key_KP_9 = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_9,

    Key_KP_Decimal  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_DECIMAL,
    Key_KP_Divide   = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_DIVIDE,
    Key_KP_Multiply = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_MULTIPLY,
    Key_KP_Subtract = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_SUBTRACT,
    Key_KP_Add      = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_ADD,
    Key_KP_Enter    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_ENTER,
    Key_KP_Equal    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_KP_EQUAL,

    Key_LeftShift     = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_LEFT_SHIFT,
    Key_LeftControl   = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_LEFT_CONTROL,
    Key_LeftAlt       = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_LEFT_ALT,
    Key_LeftSuper     = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_LEFT_SUPER,

    Key_RightShift    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_RIGHT_SHIFT,
    Key_RightControl  = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_RIGHT_CONTROL,
    Key_RightAlt      = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_RIGHT_ALT,
    Key_RightSuper    = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_RIGHT_SUPER,

    Key_Menu          = DEVICE_OFFSET_KEYBOARD + GLFW_KEY_MENU,


    // Mouse

    Mouse_Left   = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_LEFT,
    Mouse_Right  = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_RIGHT,
    Mouse_Middle = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_MIDDLE,

    Mouse_4 = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_4,
    Mouse_5 = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_5,
    Mouse_6 = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_6,
    Mouse_7 = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_7,
    Mouse_8 = DEVICE_OFFSET_MOUSE + GLFW_MOUSE_BUTTON_8,

    Mouse_Delta = DEVICE_OFFSET_MOUSE + 100,
    Mouse_Scroll = DEVICE_OFFSET_MOUSE + 101,


    // Joystick

    Joystick_1  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_1,
    Joystick_2  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_2,
    Joystick_3  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_3,
    Joystick_4  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_4,
    Joystick_5  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_5,
    Joystick_6  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_6,
    Joystick_7  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_7,
    Joystick_8  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_8,
    Joystick_9  = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_9,
    Joystick_10 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_10,
    Joystick_11 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_11,
    Joystick_12 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_12,
    Joystick_13 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_13,
    Joystick_14 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_14,
    Joystick_15 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_15,
    Joystick_16 = DEVICE_OFFSET_JOYSTICK + GLFW_JOYSTICK_16,


    // Gamepad
    
    Gamepad_A = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_A,
    Gamepad_B = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_B,
    Gamepad_X = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_X,
    Gamepad_Y = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_Y,

    Gamepad_LeftBumper  = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
    Gamepad_RightBumper = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,

    Gamepad_Back  = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_BACK,
    Gamepad_Start = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_START,
    Gamepad_Guide = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_GUIDE,

    Gamepad_LeftThumb  = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
    Gamepad_RightThumb = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,

    Gamepad_DpadUp    = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_DPAD_UP,
    Gamepad_DpadRight = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
    Gamepad_DpadDown  = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
    Gamepad_DpadLeft  = DEVICE_OFFSET_GAMEPAD + GLFW_GAMEPAD_BUTTON_DPAD_LEFT,

    Gamepad_LeftX        = DEVICE_OFFSET_GAMEPAD + 100,
    Gamepad_LeftY        = DEVICE_OFFSET_GAMEPAD + 101,
    Gamepad_RightX       = DEVICE_OFFSET_GAMEPAD + 102,
    Gamepad_RightY       = DEVICE_OFFSET_GAMEPAD + 103,
    Gamepad_LeftTrigger  = DEVICE_OFFSET_GAMEPAD + 104,
    Gamepad_RightTrigger = DEVICE_OFFSET_GAMEPAD + 105
};

struct InputInfo
{
    InputCode code = Invalid;
    std::string label = "";

    bool operator==(const InputInfo& other) const
    {
        return code == other.code; // && label == other.label
    }
};

class InputRegistry
{
public:
    static const std::vector<InputInfo>& GetInputs();
    static InputInfo GetInputInfo(const InputCode& code);
};